/*
 * Copyright 2019 ,2021 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief
 * UART2 IrDA Select: Pad RX input PTI[6] or PTE[6] selected for RX input of UART2 and UART2 TX signal is not used
 * for modulation.
 */
#define MISC_CTL_UART2IRSEL_0b0 0x00u

/*! @name PORTC2 LED_kWh
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_kWh_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED_kWh_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_kWh_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_kWh_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_kWh_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LED_kWh_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTD1 LED_kVARh
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_kVARh_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED_kVARh_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_kVARh_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_kVARh_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_kVARh_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_kVARh_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
